[options]
admin_passwd = $pbkdf2-sha512$600000$mpNyLsUYQ6jVmtNaS4kRgg$5OgFaEwGwSBMmeit9.BveHJk8.3I.CgBHIGJm0zOmIJtLQXRAedpUs4lHw7/77zkXUACbxW8NCUVyP.czd0kSA
db_host = db-odoo
db_port = 5432
db_user = odoo
db_password = odoo_password
db_name = inventario_odoo
dbfilter = ^inventario_odoo$
list_db = True
proxy_mode = False
data_dir = /var/lib/odoo

