spring.application.name=control-acceso

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/inventario_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root_password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://127.0.0.1:3000,http://localhost:8081,http://10.0.2.2:8081}

odoo.url=${ODOO_URL:http://localhost:8069}
odoo.db=${ODOO_DB:inventario_odoo}
odoo.username=${ODOO_USERNAME:admin@demo.com}
odoo.password=${ODOO_PASSWORD:123456}

app.qr-refresh-seconds=10
app.qr-grace-window-seconds=5
